### ISSUE TITLE
Support for HTML5 `required` attribute. 

### ISSUE THREAD

**Issue by ilyai** [davidstutz/bootstrap-multiselect#292]
When bootstrap-multiselect is activated it hides the original select. If the select has an `required` property it is being ignored then. Maybe it's possible to fix or workaround this, so client validation would work properly?

**Comment by 537mfb** [comment]
I think what ilyai meant is, because the original select is hidden and the added button and ul don't respond to validation as the original select would, we don't have any feedback on validation errors

With the original select we'd see a red bounding box and a balloon with an error message from the browser, while with the added button and ul we have no feedback at all

For now, the only solution seems to be to use a custom validator rather then rely on the browser's native html5 validator support

**Comment by 537mfb** [comment]
see #620 for more details on this issue
