### ISSUE TITLE
Multiselect Dropdown z-index not working inside a scroll container div

### ISSUE THREAD

**Issue by arunsasi** [davidstutz/bootstrap-multiselect#382]
In a scroll container multiselect listing not rendering propertly
My code: http://jsfiddle.net/arunsasi/7t1ask0s/
![multi](https://cloud.githubusercontent.com/assets/270789/4318465/81b2eea8-3f1e-11e4-8932-a8d1f0ef3b0a.jpg)

Please help to fix this issue :-(
Thanks

**Comment by Fclem** [comment]
This can help you fix the issue :
```
<div id="idHere" class="modal hide fade has_dropdown in" role="dialog" aria-hidden="false">
```
with
```
.has_dropdown .modal-body {
    overflow-x: visible !important;
    overflow-y: visible !important;
}
```
then
```
<ul class="multiselect-container dropdown-menu">
```
with
```
ul.dropdown-menu {
    max-height: 450px;
    overflow-y: auto;
    overflow-x: hidden;
}
```

**Comment by klodwig-yemou** [comment]
Cool solution ( inspired from davidstutz, #455  ) for **dataTables.lightColumnFilter with bootstrap-multiselect**:

```
                $("button.multiselect").on("click", function () {
                    var opened = $(this).parent().hasClass("open"); 
                    $('.dataTables_scrollHead').css("overflow", !opened?'':'hidden'); 
                });
```
It could spare someone headache ;-)

**Comment by cun3** [comment]
So is there a solution for this? Any work arounds? None of the above seem to work.

**Comment by alexFilin** [comment]
I make it works with next custom function:
 
But I have suspicions, that it can crash css styles for multiselection.
```
$("button.multiselect").on("click", function () {
    var opened = $(this).parent().hasClass("open");
    if (! opened) {
        $('.btn-group').addClass('open');
        $("button.multiselect").attr('aria-expanded', 'true');
    } else {
        $('.btn-group').removeClass('open');
        $("button.multiselect").attr('aria-expanded', 'false');
    }
});
```

**Comment by anhphuong** [comment]
That is the problem (in picture):
https://i.stack.imgur.com/Ibu5y.png

And the solution:
http://www.bootply.com/YvePJTDzI0
Just add this css code to div outside:
```
.table-responsive {
  overflow-x: visible !important;
  overflow-y: visible !important;
}
```

**Comment by jhowbhz** [comment]
Work for me

.table-responsive {
  overflow-x: visible !important;
  overflow-y: visible !important;
}

**Comment by SopoB** [comment]
$('.multiselect-container').click(function(e) 
    { 
        var containerHeight = $(this).find("ul").outerHeight();
        $(this).find(".ms-drop").css({
            'position':'fixed',
            'left':$(this).offset().left,
            'top':$(this).offset().top, 
            'height':containerHeight,
        })
    });

**Comment by sanidhyajain1** [comment]
this is not working in my file even though i have nothing else on my web page but i am using ejs is this because of that

**Comment by JohnRDOrazio** [comment]
I opened issue #1164 since after searching I hadn't found another issue dealing with this, but now I've found this thread which deals with exactly the same problem. In my opinion the cleanest solution would be that mentioned by Tyf0x [in his comment above](https://github.com/davidstutz/bootstrap-multiselect/issues/382#issuecomment-56909815), because it's not pleasant to see a parent growing in an unnatural manner just to accomodate a popup. The popup should be above the parent, which would require a rewrite of the plugin in order to place the popup in the document body. Sure this would require some work in rewriting the plugin to work this way, I would be happy to contribute if someone could perhaps point me in the right direction: what is it in the plugin that is expecting the popup to be a child of the `$container` element? See [my comment](https://github.com/davidstutz/bootstrap-multiselect/issues/1164#issue-751832398) in the issue I opened, simply trying to append to `body` rather than to `this.$container` is not enough because something is expecting to find `$popupContainer` as a child of `this.$container`. Skimming through the plugin code I haven't quite succeeded in finding what it is, perhaps it's not just the plugin code but it's a design of bootstrap in general? Sorry I'm not super familiar with bootstrap...

**Comment by robertfburke** [comment]
Because multiselect uses dropdown under the covers it's pretty easy to do using data-boundary.  Dropdowns also need to not have a relative container so adding a class to the parent control can override that so that we can control when multiselect-native-select should be relative or inherit so that it will be able to use boundary properly.

```
.multiselect-native-select-position-inherit span.multiselect-native-select {
    position: inherit;
}
```
And the button template in the JS should include data-boundary="window" or whatever other overflow container you want.

        templates: {
            button: '<button type="button" class="multiselect dropdown-toggle" data-toggle="dropdown" data-boundary="window"><span class="multiselect-selected-text"></span> <b class="caret"></b></button>',
        }

Markup in a normally relative positioned bootstrap table header cell.

```
<tr>
   <th class="multiselect-native-select-position-inherit">
      <select multiple="multiple" data-role="multiselect"></select>
   </th>
</tr>
```
