### ISSUE TITLE
Select All doesn't fire onChange event

### ISSUE THREAD

**Issue by nashtag** [davidstutz/bootstrap-multiselect#415]
Is there a way to fire the onChange event when the select all is hit?  If not, I need one please :-)

**Comment by bogal** [comment]
I too am having a bit of trouble here - i am using the standard change event to show/hide data in my document. The select all / deselect all doesn't trigger the change event - is there any other way to hook onto it?

**Comment by davidstutz** [comment]
I assume an `onSelectAll` option may be benificial here - will think about this.

**Comment by sverraest** [comment]
👍  for this feature. We're currently live updating graphs when something is selected but unfortunately this doesn't happen when you select all filters in the dropdown.

**Comment by tangledhelix** [comment]
I'm also interested in this feature. I see that there is already `onSelectAll`, but it appears to accept no params. This fires when "select all" is used, and it would be usable if only it passed in the things it is selecting. But it doesn't, so my only alternative would be to scan the DOM looking at what is or isn't selected at the moment, instead of the select telling me what it selected (or deselected, in `onDeselectAll`).

I agree a new event for each change is not warranted, but if `onSelectAll` and `onDeselectAll` had arguments, one of which was some sort of list of the changes, that would be sufficient for my purposes (which is to add or remove nodes from the DOM in a neighboring div whenever the multiselect is changed).

**Comment by Hyllesen** [comment]
Also looking for an select all onChange event here 👍

**Comment by davidstutz** [comment]
@tangledhelix Ok, I guess it is possible to adapt `onSelectAll` to provide some more information as parameters.

**Comment by khamulbr** [comment]
I am working with 6 multiselect's on the same form and need to get on which one was the SelectAll option chosen and I think I can't achieve that by the onSelectAll function or am I wrong?

Thanks !

**Comment by davidstutz** [comment]
@tangledhelix better late then never, but this will be included with the next commit.
