### ISSUE TITLE
Bootstrap very slow with lot of content

### ISSUE THREAD

**Issue by lanner** [davidstutz/bootstrap-multiselect#457]
Hello
When i open a list very long i think it's very slow, is it normal or something can do to make this more speed?

Thanks

**Comment by davidstutz** [comment]
Only when opening or are you also referring to the select all and filter features? Overall, there are several issues with the performance when using large lists - partly this is due to the large number of added features since the start of this project.

In the case you are working on a solution, you might have a look at #316, #334, #359, #268, #279, #260.

Will add this to the FAQ.

**Comment by MikeRankin** [comment]
I'm seeing really poor performance using safari with 1000 items and applying a filter.  Seems to work fine in Chrome.

**Comment by davidstutz** [comment]
Not completely solved, but several pull requests open.
