### ISSUE TITLE
Disable All selected text

### ISSUE THREAD

**Issue by Drifeter** [davidstutz/bootstrap-multiselect#466]
i don't know if this is possible (i've searched and didnt find a solution), but sometimes i have a multiselect with only one option, and in that cases the text is always "All selected".
Could it be an option to configure the All Selected text only appears when more than X options are selected?

**Comment by giano** [comment]
Would be nice! +

**Comment by ttsoft01** [comment]
I think there is actually a bug that if filtering results in multiselect (i.e. I have about a hundred golfer names in a multiselect) and you filter down to one result (i.e. type in name Arthur) and there is only one name that matches, you cannot select it without it checking "Select All" -- works perfectly if there are two or more matches to the filter.  Really annoying.

So I have to figure out how to turn off the Select All option dynamically if someone if using the filter.

**Comment by ttsoft01** [comment]
Actually, I guess it is not a bug.  It checks the "Select All" which is only one item.  So it is just misleading to the user.  I will just change the verbage to "Select All Showing" -- but that is misleading when you are only showing something like 10 items out of 100 because you have a maxsize set and someone really wants all 100 selections.

**Comment by Drifeter** [comment]
I don't think it's a bug either... Not saying that.
I just think it would be a good feature to be able to select that the "select all" text should only appear if more than 3 itens (for example) are selected.
The select box shows option 1, option 2, etc and we are able to define that after 4 itens it start appearing 4 itens selected, 5 itens selected etc... If we only have one item I think it would be good if I could show it on the select when it's selected

**Comment by ttsoft01** [comment]
I just think it is inherently confusing to still show "Select All" when filtering... users are not programmers and have difficulty understanding (as I did!), but I will go with it until an update is made.

Maybe a simple change to the words when filtering is the answer -- i.e. "smith" filter shows:  "Select All (14)" if there are 14 results -- and if no filter at all -- "Select All (100)" -- this way the user knows exactly how many the "Select All" result will contain.

I am an old COBOL programmer who started in 1981, so my ability to customize jquery to what I want is somewhat limited.  I will continue to just abuse standard features!

**Comment by davidstutz** [comment]
Ok, I am able to follow your arguments, this is definitely a problem. In general, the user experience is problematic with this plugin as it highly depends on the user and the expected behavior (e.g. when users know similar plugins behaving differently.

I think, @ttsoft01's suggestion is a good compromise, and I will add an option for this.
