### ISSUE TITLE
How use ajax to reload component?

### ISSUE THREAD

**Issue by victorgsp** [davidstutz/bootstrap-multiselect#483]
Did fill the multiselect values provided with data from an ajax request. Where the textbox the value is changed, check again to bring the new values keeping the status that was previously selected.

I am using the function:
$ ("# multiselect") multiselect ('dataprovider' date).;

When reconstructs the component the state is lost. To what was typed disappears.

Thank you for your attention.

**Comment by davidstutz** [comment]
I am afraid I do not understand your problem. You are updating/changing the options while filtering using AJAX?

**Comment by victorgsp** [comment]
The problem is the following, all examples of using multiselect component bootstrap using static values loaded at the same time that the html. I have a mass of data that can reach thousands of options to multiselect. Considering this amount would like to change the values of the options (when the User typed something) through ajax, not to have to download the entire contents of a single time.

**Comment by davidstutz** [comment]
So you want to load all options depending on the user's input into the filter?

There are several options I would recommend here:

* Use the `onDropdownShow` option to load the elements of one multiselect as soon as the user clicks the button. This way, you will not have to load ALL multiselect at once. Nevertheless, if you have several hundreds options per multiselect, this may take some time. You could consider adding a "loading" icon while the AJAX is fetching the options.
* I will see whether a `onFilerChange` event makes sense and is possible (if not you can still simply write an event handler for the created input field on your own!). Then you could actually load options whenever the user types something.

Hope these ideas help. If an `onFilterChange` is possible, I will reference this issue in the commit.

**Comment by dariobednarski** [comment]
Hi,

is there a fix for this problem? I also want to use the input text of the filter for updating the list using AJAX. Meaning, that the filter function should be disabled and instead of the filter function an ajax function should be called to update the entire options (instead of the input text field).

What I have tried yet:
Line 406 in bootstrap-multiselect: gave an id to input field:
<input class="form-control multiselect-search" id="tw-multiselect-search-input" type="text">

Added some script to my page:
$('#tw-multiselect-search-input').on('input', function(e){
                       
            if($('#tw-multiselect-search-input').val().length > 2){
                  var post = {
			searchInput: $('#tw-multiselect-search-input').val()
		  };
                  $('#loader').show();
                  var already_in_input = $('#tw-multiselect-search-input').val();
                  jQuery.ajax({
                        url      : '/search/ajaxFunction/',
                        data     : post,
                        type     : 'POST',
                        dataType : 'json',
                        success: function(data) {
                              $('#loader').hide(); 
                              var options = [
                                    {label: 'Option 1', title: 'Option 1', value: '1', selected: true},
                                    {label: 'Option 2', title: 'Option 2', value: '2'},
                                    {label: 'Option 3', title: 'Option 3', value: '3', selected: true},
                                    {label: 'Option 4', title: 'Option 4', value: '4'},
                                    {label: 'Option 5', title: 'Option 5', value: '5'},
                                    {label: 'Option 6', title: 'Option 6', value: '6', disabled: true}
                              ];
                              $('#example-getting-started').multiselect('dataprovider', options);
                              $('#tw-multiselect-search-input').val(already_in_input);
                              $('#tw-multiselect-search-input').focus();

                        }      
                  });                                                    
            }                  
      });
The new options are static yet but may be dynamically created from the server response, of course. This data is just for testing. 

So, the new multiselect gets created perfectly but after the ajax call the .on('input') function isn't excecuted anymore when I type some more characters in the input field. I think that's because a new multiselect gets created and the .on('input') function is still binded to the old one (although the new one has the same id for the input field).

I also tried to remove all options and append new options after the ajax call and then rebuild the multiselect. This solution is not nice because the rebuild forces the new multiselect to be closed again.

I need help, please!

**Comment by parveensaini1** [comment]
Hello i am also getting issue to put data into the select with dataprovider after put all my json the filter is not work.
