### ISSUE TITLE
Separate onGroupSelect event

### ISSUE THREAD

**Issue by jdsingh** [davidstutz/bootstrap-multiselect#506]
Currently if `enableClickableOptGroups` is set to `true` and user click on option group it fires `onChange` event for all the options in that group. 

I think there should be method for group click as well just like onSelectAll.

**Comment by rbsevilla** [comment]
I'm currently having problem when option group is clicked. It fires onChange times number of options in the group.

**Comment by naomap** [comment]
I'm running into the same problem, and I'd argue this is a bug. When includeSelectAllOption is true, onChange is fired only once. When using optGroups, onChange is indeed fired for each option in the group. 

So rather than adding a new event handler, onChange could (should?) be fired once when an optGroup is clicked - after all values have been selected or cleared.

**Comment by ccshine** [comment]
I'm having the same problem too.  When the number of items under an optGroup exceeds approximately 25, it takes at least 5 seconds to select all the items in the optGroup.  This is unacceptable since there isn't a way to present any kind of "Please wait" message to pacify the user.  My only alternative aside from hacking into the js is having 2 cascading muliselects and not using optGroups.  Sad since this is effectively already built into this control.

I agree onChange should only be fired once for optGroups.  Otherwise it becomes unusable for a large list of items.

**Comment by rbsevilla** [comment]
I hope someone could help us :(

**Comment by ccshine** [comment]
I got desperate and made a copy of the js file for the page that used optGroups with a lot of items.  Discovered the major hosage was occurring on a few lines (~512-535) and commented the following out. 

if (this.options.selectedClass === "active") {
     $optionsNotThis.closest("a").css("outline", "");
}

this.updateButtonText();
this.updateSelectAll();

Didn't really see the display difference for the css section.  And I compensate for the last 2 lines by including the following onDropdownHide for each multiselect declaration.  Not the most elegant solution, but it'll work until hopefully this is fixed.  Since it does seem like a bug to me too.

onDropdownHide: function (event) {
     $("select[id$='ddlSystem']").multiselect("updateButtonText");
     $("select[id$='ddlSystem']").multiselect("updateSelectAll");
}
