### ISSUE TITLE
Simple demo

### ISSUE THREAD

**Issue by ryanhellyer** [davidstutz/bootstrap-multiselect#520]
I think an extremely simple demo should be included, to make it easier to figure out how to use the code.

For example, I managed to shorten +118 kB of CSS down to just this:
```
.btn-group .multiselect-container {display: none}
.open .multiselect-container {display: block}
```

**Comment by davidstutz** [comment]
+118kB of CSS is including Bootstrap right? Because the multiselect CSS is 2kb and the Javascript something around 55kb.

And shortening the CSS might be interesting for some users, but the easiest ways to use the plugin is simply including the original CSS and JS (2 includes) and call the plugin (1 line call + `select` code). I think for many useres it might be more work to adapt the CSS file especially if some of the more complex options are used.

However, feel free to include your demo.
