### ISSUE TITLE
Label positioning and width question (issue?) [Please close it]

### ISSUE THREAD

**Issue by jujiro** [davidstutz/bootstrap-multiselect#586]
I have the following markup:

```javascript
<div class="form-group">
	<label for="cbCountry">Country</label>
	<select id="cbCountry" class="form-control" multiple="multiple">
		<option value="1">USA</option>
		<option value="2">Australia</option>
	</select>
</div>
```

Which renders like this (as expected):
![clip2](https://cloud.githubusercontent.com/assets/6651099/8782297/6dca90c6-2ee2-11e5-820f-e8848920115e.jpg)

With multi-select activated, the form essentially starts behaving as horizontal and I lose control over the width too, unless I specify it explicitly in the multi-select options, which would defeat the purpose.
![clip1](https://cloud.githubusercontent.com/assets/6651099/8782336/b7673824-2ee2-11e5-8818-1f75433b6226.jpg)

Is there a way to handle this and make it behave like the expected bootstrap behavior?

**Comment by jujiro** [comment]
Found the solution by specifying the width to be "100%".

**Comment by wvengen** [comment]
I'm bumping into this as well. Even `inheritClass` doesn't solve this, since the class is set for the multiselect button, not its container, which retails `display: inline-block` causing this behaviour.
Not sure what a clean solution would be, though.
(I was a bit surprised that the button was wrapped in a `btn-group` container div, perhaps that shouldn't be the default.)
