### ISSUE TITLE
Simplest code just not working. Why?

### ISSUE THREAD

**Issue by davidmz** [davidstutz/bootstrap-multiselect#597]
I wrote this minimal page (just one select): https://jsfiddle.net/cs4Lha4r/3/ 

As you can see, drop-down menu not working. Why?

**Comment by Aidurber** [comment]
Hi David, 

I too couldn't get it working on JSFiddle, however I can get it working locally with the code you provided. I think the issue is with code playgrounds like JSFiddle (I tried JSBin too). Can you please try it locally and with downloaded libraries instead of linking to the raw code on Github?

**Comment by davidmz** [comment]
I'm sorry, it is my mistake: I just forgot to include bootstrap.min.js into my page.

**Comment by Aidurber** [comment]
Hah, no worries, I missed that too.
