### ISSUE TITLE
options with 50k+

### ISSUE THREAD

**Issue by zeyabadar** [davidstutz/bootstrap-multiselect#778]
Hi,

Thanks for your plugin,Really I liked it too much and it is fit as per my requirement.

But I have 50k+ records to bind with drop-down.When I am binding with 50k record the browser got freezed. So what i think, I will bring only 100 records from database and display in drop-down.When user will search using text-box I will bring all the records relevant to his search from database and show to drop-down list option. I need to maintain all the selected options on different search results.

Can we do this kind of search and maintain all selected options using this plugin?

I am asking like auto complete kind of thing which will bring data using ajax call on search and maintain all the selected options. 

Could you please help me on this?Thanks in advance.

**Comment by tiesont** [comment]
This plugin does not provide that functionality. You would need to implement it yourself. Sounds like you might be better off implementing a search box, only loading the matching items into the multi-select.

**Comment by zeyabadar** [comment]
Thanks @tiesont  for your comments. I will try to implement it as per my requirement. Actually my requirement is little tricky.

**Comment by niyazpk** [comment]
For anyone else who wants to use this wonderful component with a large number of options:

You will need to fix a lot of performance issues in this plugin. The good news is that there are a LOT of opportunities for improving performance in this plugin. The bad news is that it is not a trivial amount of work to get it done.

I have a local copy (with some features stripped) that performs around 50x better (in time to render) than this version. It is not in a shippable form yet though.

If you go down this path, the lowest hanging fruit to attack will be to replace all the event bind calls in  loops to a single delegated bind on the parent. So instead of calling bind() on all the lis for example, call bind on the ul once and handle it. This itself should improve your performance by a lot. Chrome's profiler is a _great_ tool for this. Use, it! It will tell you what/where you should look at to fix your performance bottlenecks.

Meanwhile if i ever get to cleanup some of my code, I will post the PR or something here.

**Comment by Dams591** [comment]
Hey @niyazpk 
I'm interested into better performances too, are you getting any closer on this ? 
Thanks,

**Comment by davidstutz** [comment]
@niyazpk: feel free to share your speed improvements (as PR, or just for reference).
@zeyabadar: there was a pull request about AJAX search in past you can checkout.

I'll close this issue; the speed improvements have already been addressed in several issues and there is no concrete feature requested/bug reported here.
