### ISSUE TITLE
Question: Autoselect filtered value

### ISSUE THREAD

**Issue by evanpratama** [davidstutz/bootstrap-multiselect#940]
Hello All,

This is not actually an issue, but just a question.

What I intended to do is to filter the option, then autoselect all the displayed options based on that filter (update the button too). This is what i've implemented so far:

http://jsfiddle.net/evanpratama/mqw7pLzk/

I added an event handler on the filter input box, clear the current selection, and select all the visible ones.

The issue i've faced at this stage is that it is not updating the selection:
For example: I have options of : Team1, Team2, Tech1, Tech2
On the filter input, I typed in Tec - it displays Tech1 and Tech2, and checked, but it does not update the button text. if I press space afterwards, then it updates the button text with Tech1 and Tech2 although there is no displayed options.

Can anyone give me a pointer on how to solve this?

Thanks!

**Comment by davidstutz** [comment]
The button text is not the problem. The problem is that after typing 'tec', still all 4 options are selected (as you can see using your logging messages).

Short debugging suggests that the `selectAll` call is the problem. `selectAll` does not seem to select the currently visible option after filtering, but before filtering. So after entering 'tec', `selectAll` still finds all options visible, but after typing 'tech' only two options are visible.

This might actually be caused by the fact that your event handler on keyup is processed before multiselects internal event handler for filtering the options is processed. This would explain the behavior. I just can't test it right now. Let me now if you get it working.
